# ref: https://dev.to/supersuman/build-and-sign-android-apps-using-github-actions-54j
name: Android QA Build CD

on: [ workflow_dispatch ]

jobs:
  qa-build-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: zulu
            java-version: 17

      - name: Build APK
        run: ./gradlew assembleRelease PstorePassword=${{secrets.PPAC_KEYSTORE_PASSWORD}} PkeyPassword=${{PPAC_ALIAS_PASSWORD}}

      - name: Upload Build to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.PPAC_FIREBASE_APP_ID }}
            serviceCredentialsFileContent: ${{ secrets.PPAC_FIREBASE_CREDENTIAL }}
            groups: android-tester
            file: app/build/outputs/apk/release/app-release.apk
            # app/build/outputs/apk/standard/stage/release/app-standard-stage-release.apk