# ref: https://dev.to/supersuman/build-and-sign-android-apps-using-github-actions-54j
name: Android QA Build CD

on: [ workflow_dispatch ]

jobs:
  qa-build-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Create Local Properties
        run: |
          echo "${{ secrets.PPAC_LOCAL_PROPERTIES }}" > ./local.properties

      - name: Create file
        run: cat /home/runner/work/ppac-android/ppac-android/app/google-services.json | base64

      - name: Putting data
        env:
          DATA: ${{ secrets.PPAC_GOOGLE_SERVICES }}
        run: echo $DATA > /home/runner/work/ppac-android/ppac-android/app/google-services.json

      - name: Create KeyStore Properties
        run: |
          echo "${{ secrets.PPAC_KEYSTORE_PROPERTIES }}" > ./farmeme-keystore.properties

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload Build to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.PPAC_FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.PPAC_FIREBASE_CREDENTIAL }}
          groups: android-tester
          file: app/build/outputs/apk/debug/app-debug.apk